// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package postgres

import (
	"context"
	"database/sql"
)

const addPerson = `-- name: AddPerson :execresult
INSERT INTO persons (
	person_name, phone, addressID
) VALUES (
	?, ?, ?
)
`

type AddPersonParams struct {
	PersonName string
	Phone      string
	Addressid  int32
}

func (q *Queries) AddPerson(ctx context.Context, arg AddPersonParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addPerson, arg.PersonName, arg.Phone, arg.Addressid)
}
