// Code generated by sqlc. DO NOT EDIT.

package queries

import (
	"database/sql"
)

type Address struct {
	ID         int32
	Country    string
	City       string
	Street     string
	House      string
	Apartments sql.NullString
}
